common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    meson : "eta" 
    period : "LHC220"
    do_ptspectrum: True
    # pt_bin: [0., 0.2, 0.3, 0.40,  0.50, 0.60, 0.70, 0.80, 0.90, 1.00, 1.20, 1.40, 1.60, 1.80, 2.0, 2.50, 3.00,  3.50, 4.00, 4.50, 5.00, 5.5, 6.00,  7.00, 8.00, 9.00, 15.0]
    pt_bin: [0., 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 5.0, 10.0, 20.0]
    start_pT_bin: 3

    fit_min: [0.4]
    fit_max: [0.7]
    integral_min: [0.65]
    integral_max: [0.7]
    yield_min: [0.065]
    yield_max: [0.04]

data:
    fit_func: ["gausexplinear"] 
    fit_parameters: [0,0,0,0,0]
    fit_limit_min: [0,0,0,0,0]
    fit_limit_max: [0,0,0,0,0]
    subsystems: 
        - name: "pi0eta-to-gammagamma-pcmdalitzee"
          mc_name: "pi0eta-to-gammagamma-mc-pcmdalitzee"
          fit_parameters: [height,mean_init,sigma_init,lambda_init, 50, -100]
          fit_limit_min: [0.95,0.926,0.5,0.65]
          fit_limit_max: [2.5,1.02,1.3,1.1]
        - name: "pi0eta-to-gammagamma-pcmdalitzee_itsibany"
          mc_name: "pi0eta-to-gammagamma-mc-pcmdalitzee_itsibany"
          fit_parameters: [height,mean_init,sigma_init,lambda_init, 50, -100]
          fit_limit_min: [0.95,0.926,0.5,0.65]
          fit_limit_max: [2.5,1.02,1.3,1.1]
          
mc:
    fit_func: ["gausexp"] 
    subsystems: 
        - "pi0eta-to-gammagamma-pcmdalitzee"
        - "pi0eta-to-gammagamma-pcmdalitzee_itsibany"
         
