common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    meson : "pi0" 
    period : "LHC22o"
    do_ptspectrum: True
    pt_bin: [0, 0.2, 0.4, 0.8, 1.2, 1.6, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0, 12.0]
    fit_min: [0.04] # previously 0.06
    fit_max: [0.2] 
    integral_min: [0.18]
    integral_max: [0.25]
    yield_min: [0.035]
    yield_max: [0.02] # previously 0.01
    leg_entry: "M.C. rec. #gamma (LHC24b1)"
data:
    fit_func: ["gausexplinear"] 
    fit_parameters: [0,0,0,0,0]
    fit_limit_min: [0,0,0,0,0]
    fit_limit_max: [0,0,0,0,0]
    subsystems: 
        
        - name: "PCMDalitzEE"
          cuts:
            - name: "qc_mee0_60_minpt100_maxeta09_tpconly_lowB"
              # initial values: height = 
              fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
              fit_limit_min: [0.99,0.926,0.8,0.85]
              fit_limit_max: [1.2,1.02,1.6,1.5]
          
        #     max: [1.2,1.02,1.6,1.5]
            - name: "qc_pc_itsib"
              # initial values: []
              fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
              fit_limit_min: [0.97,0.926,0.85,0.8]
              fit_limit_max: [1.2,1.02,1.5,1.1]
mc:
    fit_func: ["gausexp"] 
    fit_parameters: [0,0,0,0,0]
    fit_limit_min: [0,0,0,0,0]
    fit_limit_max: [0,0,0,0,0]
    subsystems: 

        - name: "PCMDalitzEE"
          cuts:
              - name: "qc_mee0_60_minpt100_maxeta09_tpconly_lowB"
              # initial values: []
                fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
                fit_limit_min: [0.999,0.926,0.6,0.6]
                fit_limit_max: [1.1,1.02,1.5,1.2]
              - name: "qc_pc_itsib"
              # initial values: []
                fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
                fit_limit_min: [0.999,0.926,0.6,0.6]
                fit_limit_max: [1.1,1.02,1.5,1.2]
        
