common:
    system : "pp"
    energy : 13.6 #center-of-mass energy in TeV
    meson : "pi0" 
    period : "LHC22o"
    do_ptspectrum: True
    # pt_bin: [0., 0.2, 0.40,  0.50, 0.60, 0.70, 0.80, 0.90, 1.00, 1.20, 1.40, 1.60, 1.80, 2.0, 2.50, 3.00,  3.50, 4.00, 4.50, 5.00, 5.5, 6.00,  7.00, 8.00, 9.00, 15.0, 20.0]
    pt_bin: [0., 0.50, 1.00, 1.25, 1.5, 2.0, 2.50, 3.00, 4.00, 5.00, 7.00, 20.0]
    
    # pt_bin: [0., 0.5, 1.0, 1.5, 2.0, 2.5, 3.5, 6.0, 10.0, 20.0]
    start_pT_bin: 1
    fit_min: [0.04] # previously 0.06
    fit_max: [0.2] 
    integral_min: [0.18]
    integral_max: [0.25]
    yield_min: [0.035]
    yield_max: [0.02] # previously 0.01
data:
    fit_func: ["gausexplinear"] 
    fit_parameters: [0,0,0,0,0]
    fit_limit_min: [0,0,0,0,0]
    fit_limit_max: [0,0,0,0,0]
    subsystems: 
      #  - name: "PCMPCM"
      #    cuts:
        - name: "pi0eta-to-gammagamma-pcmpcm"
          mc_name: "pi0eta-to-gammagamma-mc-pcmpcm"
          fit_parameters: [height,mean_init,sigma_init,lambda_init,50, -100]
          fit_limit_min: [0.95,0.926,0.5,0.65]
          fit_limit_max: [1.2,1.02,1.3,1.1]
          
mc:
    fit_func: ["gausexp"] 
    subsystems: 
        # - name: "PCMPCM"
        #   cutnames:
        - "pi0eta-to-gammagamma-pcmpcm"
        
